include ../../global_config

OBJS = $(OBJDIR)/timefront.o \
	../colors/$(OBJDIR)/plugincolors.o

OUTPUT = ../$(OBJDIR)/timefront.plugin

include ../../plugin_config


$(OBJDIR)/timefront.o: timefront.C
