include ../../global_config

OBJS = $(OBJDIR)/chromakey.o  \
	../colors/$(OBJDIR)/colorpicker.o \
	../colors/$(OBJDIR)/plugincolors.o

OUTPUT = ../$(OBJDIR)/chromakey.plugin

include ../../plugin_config


$(OBJDIR)/chromakey.o: chromakey.C
