include ../../global_config

OBJS = \
	../motion/$(OBJDIR)/affine.o \
	$(OBJDIR)/perspective.o

OUTPUT = ../$(OBJDIR)/perspective.plugin

include ../../plugin_config

$(OBJDIR)/perspective.o: perspective.C
