include ../../global_config

OBJS := \
	$(OBJDIR)/affine.o \
	$(OBJDIR)/motion.o \
	$(OBJDIR)/motionwindow.o

OUTPUT := ../$(OBJDIR)/motion.plugin

include ../../plugin_config

$(OBJDIR)/affine.o: affine.C
$(OBJDIR)/motion.o: motion.C
$(OBJDIR)/motionwindow.o: motionwindow.C
