include ../../global_config

OBJS = \
	../motion/$(OBJDIR)/affine.o \
	$(OBJDIR)/radialblur.o

OUTPUT = ../$(OBJDIR)/radialblur.plugin

include ../../plugin_config

$(OBJDIR)/radialblur.o: radialblur.C
