include ../../global_config

OBJS = $(OBJDIR)/gamma.o  \
	$(OBJDIR)/gammawindow.o \
	../colors/$(OBJDIR)/plugincolors.o

OUTPUT = ../$(OBJDIR)/gamma.plugin

include ../../plugin_config

$(OBJDIR)/gamma.o: gamma.C
$(OBJDIR)/gammawindow.o: gammawindow.C
